-- Инициализация схемы Firebird 3.0 (Часть II задания)
-- Firebird 3.0 НЕ поддерживает CREATE TABLE IF NOT EXISTS,
-- поэтому скрипт должен выполняться один раз (см. firebird-init сервис в compose)

CREATE TABLE institutions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE student_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    course INTEGER NOT NULL,
    status VARCHAR(50) DEFAULT 'active' NOT NULL
);

CREATE TABLE students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    group_id INTEGER NOT NULL,
    institution_id INTEGER NOT NULL,
    status VARCHAR(50) DEFAULT 'active' NOT NULL,
    CONSTRAINT fk_students_group
        FOREIGN KEY (group_id) REFERENCES student_groups(id),
    CONSTRAINT fk_students_institution
        FOREIGN KEY (institution_id) REFERENCES institutions(id)
);

CREATE TABLE exams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    exam_date DATE NOT NULL,
    group_id INTEGER NOT NULL,
    CONSTRAINT fk_exams_group
        FOREIGN KEY (group_id) REFERENCES student_groups(id)
);

CREATE TABLE exam_results (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    exam_id INTEGER NOT NULL,
    grade INTEGER,
    status VARCHAR(50) DEFAULT 'scheduled' NOT NULL,
    CONSTRAINT fk_results_student
        FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_results_exam
        FOREIGN KEY (exam_id) REFERENCES exams(id)
);

COMMIT;

-- Демо-данные для проверки CRUD
INSERT INTO institutions (name) VALUES ('Колледж №1');
INSERT INTO institutions (name) VALUES ('Колледж №2');

INSERT INTO student_groups (name, course, status) VALUES ('ИС-21', 2, 'active');
INSERT INTO student_groups (name, course, status) VALUES ('ПР-19', 3, 'active');

INSERT INTO students (full_name, group_id, institution_id, status) VALUES ('Иванов Иван Иванович', 1, 1, 'active');
INSERT INTO students (full_name, group_id, institution_id, status) VALUES ('Петров Петр Петрович', 2, 1, 'active');

INSERT INTO exams (name, exam_date, group_id) VALUES ('Программирование', '2026-01-15', 1);
INSERT INTO exams (name, exam_date, group_id) VALUES ('Базы данных', '2026-01-20', 2);

INSERT INTO exam_results (student_id, exam_id, grade, status) VALUES (1, 1, 5, 'passed');
INSERT INTO exam_results (student_id, exam_id, grade, status) VALUES (2, 2, 4, 'passed');

COMMIT;
