server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=10s;

    # /api/...  ->  python-api (FastAPI + Firebird)
    location /api/ {
        set $upstream http://python-api:8000;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass $upstream;
    }
}
